### ISSUE TITLE
Release to npm with destroy method

### ISSUE THREAD

**Issue by kentmw** [the-diamond-dogs-group-oss/scrollpoints#3]
I'd like to remove an added scrollpoints. It looks like you have added a destroy method. When are you planning on releasing again?

**Comment by ferdinandtorggler** [comment]
Hi,

thanks for using our script. Currently I don't have much time, but I think
this is a good idea and worth adding.
I'm not sure if it can be done without breaking backwards compatibility. I
would need to return an individual scrollpoint or some identifier from the
add method to reference it later (which will break the ability to chain
add() calls). I'll think of a solution in the meantime.

Best regards,
Ferdinand

**Comment by ferdinandtorggler** [comment]
For now I published v0.4.0 with the destroy method to npm. But keep in mind that destroy will remove all the added scrollpoints, see my previous answer about removing individual ones.
